name: Apply Deploy Label

on:
  pull_request:
    types: [labeled]

jobs:
  build_and_deploy_job:
    if: github.event.label.name == 'Accept for Deploy'
    runs-on: ubuntu-latest
    name: Accept
    steps:
      - name: Accept
        run: echo "Accepted"
