name: Apply Deploy Label

on:
  pull_request:
    types: [labeled]

jobs:
  build_and_deploy_job:
    if: github.event.label.name == 'Accept for Deploy'
    runs-on: ubuntu-latest
    name: Accept
    steps:
      - name: Accept
        run: echo "Accepted"

  close_pull_request_job:
    if: github.repository != 'chili-publish/grafx-documentation' && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_SKY_012B9BC03 }}
          action: "close"
