name: Apply Deploy Label

on:
  pull_request:
    types: [labeled]

jobs:
  save-pr-info:
    if: github.event.label.name == 'Accept for Deploy'
    runs-on: ubuntu-latest
    name: Save PR info for fork deploy
    steps:
      - name: Save PR data
        run: |
          mkdir -p ./pr
          echo "${{ github.event.pull_request.number }}"   > ./pr/number
          echo "${{ github.event.pull_request.head.sha }}" > ./pr/sha
      - name: Upload PR info artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
