on:
  push:
    branches:
      - main
      - feature/deploy-action
jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install MkDocs
        run: pip install mkdocs-material
      - name:  build documentation 
        run: mkdocs build
      - name: deploy build to server via sftp
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: '${{ secrets.DOCUMENTATION_OVH_USERNAME }}'
            server: '${{ secrets.DOCUMENTATION_OVH_IP }}'
            password: '${{ secrets.DOCUMENTATION_OVH_PWD }}'
            ssh_private_key: 'bla'
            local_path: './site/*'
            remote_path: '/var/www/grafxdocs'
            sftpArgs: '-o ConnectTimeout=5'
            port: 22